name: Publish to npm (provenance)

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write    # required by provenance/signing in GitHub Actions workflows

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Publish to npm with provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"
        run: npm publish --access public --provenance
